# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3053a63a8705d72965ebfc28d10cf51a98a5a6b040974f20d5ff158a9cb1ff4f1691b3805dd6d3a1cbbd9385201b8c8ed3dce3bfa510b7540e57651a59fdfd06

test:
  secret_key_base: db695028c63838aa0204d0c50d411dc96f69382d375c6d4ca127f5889596e45ce524191c57b9d146d5be361e95d56c6e113a70390d34a0f75c3ea647ed8e6329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
